import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "2rem",
          fontSize: "1.5rem",
          padding: "3rem",
        }}
      >
        {data.map((d) => (
          <div key={d.id}>
            {d.id}) {d.title} - ${d.price}
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const protocol = req.headers["x-forwarded-proto"] || "http";
  const baseURL = `${protocol}://${req.headers.host}/api/hello`;
  const { data } = await axios.get(baseURL);

  return {
    props: {
      data,
    },
  };
}
